services:
  api:
    image: ghcr.io/romartm/freesslcert.net/api:latest
    container_name: freesslcert-api
    restart: always
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - "traefik.http.routers.freesslcert.rule=Host(`api.freesslcert.net`)"
      - traefik.http.routers.freesslcert.entrypoints=websecure
      - traefik.http.routers.freesslcert.tls=true
      - traefik.http.services.freesslcert.loadbalancer.server.port=8080
    networks:
      - traefik-public
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik-public:
    external: true
